folder_export: data_ext/

find_urls:
    data_yml:
        config: 
            name: 'ejemplo'
            folder: 'inicial'
            size_screen: '1420,1080'
            compare: ''
        pages: []
    number_limit: 50

